#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM_QLGTDD
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PM_QLGTDD")]
	public partial class DB_QLGTDDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBIEUMAU(BIEUMAU instance);
    partial void UpdateBIEUMAU(BIEUMAU instance);
    partial void DeleteBIEUMAU(BIEUMAU instance);
    partial void InsertLOAIBIEUMAU(LOAIBIEUMAU instance);
    partial void UpdateLOAIBIEUMAU(LOAIBIEUMAU instance);
    partial void DeleteLOAIBIEUMAU(LOAIBIEUMAU instance);
    #endregion
		
		public DB_QLGTDDDataContext() : 
				base(global::PM_QLGTDD.Properties.Settings.Default.PM_QLGTDDConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DB_QLGTDDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_QLGTDDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_QLGTDDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_QLGTDDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BIEUMAU> BIEUMAUs
		{
			get
			{
				return this.GetTable<BIEUMAU>();
			}
		}
		
		public System.Data.Linq.Table<LOAIBIEUMAU> LOAIBIEUMAUs
		{
			get
			{
				return this.GetTable<LOAIBIEUMAU>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BIEUMAU")]
	public partial class BIEUMAU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _QUYENSO;
		
		private System.Nullable<int> _SO;
		
		private string _HOTEN_NVD;
		
		private System.Nullable<System.DateTime> _NGAYVIETDON;
		
		private System.Nullable<int> _ID_LOAIBIEUMAU;
		
		private bool _TT_XUAT;
		
		private bool _TT_XOA;
		
		private EntityRef<LOAIBIEUMAU> _LOAIBIEUMAU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnQUYENSOChanging(System.Nullable<int> value);
    partial void OnQUYENSOChanged();
    partial void OnSOChanging(System.Nullable<int> value);
    partial void OnSOChanged();
    partial void OnHOTEN_NVDChanging(string value);
    partial void OnHOTEN_NVDChanged();
    partial void OnNGAYVIETDONChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYVIETDONChanged();
    partial void OnID_LOAIBIEUMAUChanging(System.Nullable<int> value);
    partial void OnID_LOAIBIEUMAUChanged();
    partial void OnTT_XUATChanging(bool value);
    partial void OnTT_XUATChanged();
    partial void OnTT_XOAChanging(bool value);
    partial void OnTT_XOAChanged();
    #endregion
		
		public BIEUMAU()
		{
			this._LOAIBIEUMAU = default(EntityRef<LOAIBIEUMAU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUYENSO", DbType="Int")]
		public System.Nullable<int> QUYENSO
		{
			get
			{
				return this._QUYENSO;
			}
			set
			{
				if ((this._QUYENSO != value))
				{
					this.OnQUYENSOChanging(value);
					this.SendPropertyChanging();
					this._QUYENSO = value;
					this.SendPropertyChanged("QUYENSO");
					this.OnQUYENSOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SO", DbType="Int")]
		public System.Nullable<int> SO
		{
			get
			{
				return this._SO;
			}
			set
			{
				if ((this._SO != value))
				{
					this.OnSOChanging(value);
					this.SendPropertyChanging();
					this._SO = value;
					this.SendPropertyChanged("SO");
					this.OnSOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN_NVD", DbType="NVarChar(50)")]
		public string HOTEN_NVD
		{
			get
			{
				return this._HOTEN_NVD;
			}
			set
			{
				if ((this._HOTEN_NVD != value))
				{
					this.OnHOTEN_NVDChanging(value);
					this.SendPropertyChanging();
					this._HOTEN_NVD = value;
					this.SendPropertyChanged("HOTEN_NVD");
					this.OnHOTEN_NVDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYVIETDON", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYVIETDON
		{
			get
			{
				return this._NGAYVIETDON;
			}
			set
			{
				if ((this._NGAYVIETDON != value))
				{
					this.OnNGAYVIETDONChanging(value);
					this.SendPropertyChanging();
					this._NGAYVIETDON = value;
					this.SendPropertyChanged("NGAYVIETDON");
					this.OnNGAYVIETDONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOAIBIEUMAU", DbType="Int")]
		public System.Nullable<int> ID_LOAIBIEUMAU
		{
			get
			{
				return this._ID_LOAIBIEUMAU;
			}
			set
			{
				if ((this._ID_LOAIBIEUMAU != value))
				{
					if (this._LOAIBIEUMAU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_LOAIBIEUMAUChanging(value);
					this.SendPropertyChanging();
					this._ID_LOAIBIEUMAU = value;
					this.SendPropertyChanged("ID_LOAIBIEUMAU");
					this.OnID_LOAIBIEUMAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TT_XUAT", DbType="Bit NOT NULL")]
		public bool TT_XUAT
		{
			get
			{
				return this._TT_XUAT;
			}
			set
			{
				if ((this._TT_XUAT != value))
				{
					this.OnTT_XUATChanging(value);
					this.SendPropertyChanging();
					this._TT_XUAT = value;
					this.SendPropertyChanged("TT_XUAT");
					this.OnTT_XUATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TT_XOA", DbType="Bit NOT NULL")]
		public bool TT_XOA
		{
			get
			{
				return this._TT_XOA;
			}
			set
			{
				if ((this._TT_XOA != value))
				{
					this.OnTT_XOAChanging(value);
					this.SendPropertyChanging();
					this._TT_XOA = value;
					this.SendPropertyChanged("TT_XOA");
					this.OnTT_XOAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIBIEUMAU_BIEUMAU", Storage="_LOAIBIEUMAU", ThisKey="ID_LOAIBIEUMAU", OtherKey="ID_LOAIBIEUMAU", IsForeignKey=true)]
		public LOAIBIEUMAU LOAIBIEUMAU
		{
			get
			{
				return this._LOAIBIEUMAU.Entity;
			}
			set
			{
				LOAIBIEUMAU previousValue = this._LOAIBIEUMAU.Entity;
				if (((previousValue != value) 
							|| (this._LOAIBIEUMAU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAIBIEUMAU.Entity = null;
						previousValue.BIEUMAUs.Remove(this);
					}
					this._LOAIBIEUMAU.Entity = value;
					if ((value != null))
					{
						value.BIEUMAUs.Add(this);
						this._ID_LOAIBIEUMAU = value.ID_LOAIBIEUMAU;
					}
					else
					{
						this._ID_LOAIBIEUMAU = default(Nullable<int>);
					}
					this.SendPropertyChanged("LOAIBIEUMAU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIBIEUMAU")]
	public partial class LOAIBIEUMAU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_LOAIBIEUMAU;
		
		private string _TENBIEUMAU;
		
		private EntitySet<BIEUMAU> _BIEUMAUs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_LOAIBIEUMAUChanging(int value);
    partial void OnID_LOAIBIEUMAUChanged();
    partial void OnTENBIEUMAUChanging(string value);
    partial void OnTENBIEUMAUChanged();
    #endregion
		
		public LOAIBIEUMAU()
		{
			this._BIEUMAUs = new EntitySet<BIEUMAU>(new Action<BIEUMAU>(this.attach_BIEUMAUs), new Action<BIEUMAU>(this.detach_BIEUMAUs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOAIBIEUMAU", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_LOAIBIEUMAU
		{
			get
			{
				return this._ID_LOAIBIEUMAU;
			}
			set
			{
				if ((this._ID_LOAIBIEUMAU != value))
				{
					this.OnID_LOAIBIEUMAUChanging(value);
					this.SendPropertyChanging();
					this._ID_LOAIBIEUMAU = value;
					this.SendPropertyChanged("ID_LOAIBIEUMAU");
					this.OnID_LOAIBIEUMAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENBIEUMAU", DbType="NVarChar(500)")]
		public string TENBIEUMAU
		{
			get
			{
				return this._TENBIEUMAU;
			}
			set
			{
				if ((this._TENBIEUMAU != value))
				{
					this.OnTENBIEUMAUChanging(value);
					this.SendPropertyChanging();
					this._TENBIEUMAU = value;
					this.SendPropertyChanged("TENBIEUMAU");
					this.OnTENBIEUMAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIBIEUMAU_BIEUMAU", Storage="_BIEUMAUs", ThisKey="ID_LOAIBIEUMAU", OtherKey="ID_LOAIBIEUMAU")]
		public EntitySet<BIEUMAU> BIEUMAUs
		{
			get
			{
				return this._BIEUMAUs;
			}
			set
			{
				this._BIEUMAUs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BIEUMAUs(BIEUMAU entity)
		{
			this.SendPropertyChanging();
			entity.LOAIBIEUMAU = this;
		}
		
		private void detach_BIEUMAUs(BIEUMAU entity)
		{
			this.SendPropertyChanging();
			entity.LOAIBIEUMAU = null;
		}
	}
}
#pragma warning restore 1591
